chaos_monkey: 
  run_time: 10
  min_containers: 2
  max_containers: 5
  base_url: http://192.168.99.100:2375
  start:
    policy: random
    interval: 8
    workers: 1
    exempt_containers:
      - haproxy
      - chaos-monkey
      - docker-http
  kill:
    policy: random
    interval: 8
    workers: 2
    exempt_containers:
      - haproxy
      - chaos-monkey
      - docker-http
  docker_remote_api_version: "1.20"